version: 0.0
os: windows
files:
  - source: \SampleASPNetApp
    destination: c:\inetpub\wwwroot
file_exists_behavior: OVERWRITE
  
hooks:
  BeforeInstall:
    - location: .\StopServer.ps1
  AfterInstall:
    - location: .\StartServer.ps1
