version: 0.0
os: windows
files:
  - source: \SampleASPNetApp
    destination: c:\inetpub\wwwroot
  
hooks:
  BeforeInstall:
    - location: .\StopServer.ps1
  AfterInstall:
    - location: .\StartServer.ps1
